M48
; DRILL file {KiCad (6.0.2)} date Sun 13 Feb 2022 11:21:48 AM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-13T11:21:48-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T2
X0.1969Y-0.1969
X0.1969Y-1.7717
X2.9528Y-0.1969
X2.9528Y-1.7717
T0
M30
